campaigns/urls.py
__author__ = 'davidkavanagh'

from django.conf.urls import patterns, url
from campaigns import views

urlpatterns = patterns('',
    # Examples:
    url(r'^$', views.list_campaigns, name='list_campaigns'),
    url(r'^listCampaigns/$', views.list_campaigns, name='list_campaigns'),
    url(r'^showCampaign/(?P<campaign_id>\d+)/$', views.show_campaign, name='show_campaign'),
    url(r'^addCampaign/$', views.add_campaign, name='add_campaign'),
    url(r'^editCampaign/(?P<campaign_id>\d+)/$', views.add_campaign, name='edit_campaign'),
    url(r'^deleteCampaign/(?P<campaign_id>\d+)/$', views.delete_campaign, name='delete_campaign'),
)

characters/urls.py
__author__ = 'davidkavanagh'

from django.conf.urls import patterns, url
from characters import views

urlpatterns = patterns('',
    # Examples:
    url(r'^listCharacters/$', views.list_characters, name='list_characters'),
    url(r'^showCharacter/(?P<character_id>\d+)/$', views.show_character, name='show_character'),
    url(r'^addCharacter/$', views.add_character, name='add_character'),
    url(r'^editCharacter/(?P<character_id>\d+)/$', views.add_character, name='edit_character'),
    url(r'^deleteCharacter/(?P<character_id>\d+)/$', views.delete_character, name='delete_character'),
    url(r'^addXP/(?P<character_id>\d+)/$', views.add_xp, name='add_xp'),
)

opentable/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from opentable import views

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'opentable.views.home', name='home'),
    url(r'^', include('characters.urls', namespace='characters')),
    url(r'^writeups/', include('writeups.urls', namespace='writeups')),
    url(r'^campaigns/', include('campaigns.urls', namespace='campaigns')),
    url(r'^players/', include('players.urls', namespace='players')),
    url(r'^numbers/', 'opentable.views.numbers', name='numbers'),
    url(r'^about/', 'opentable.views.about', name='about'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', 'opentable.views.user_login', name='login'),
    url(r'^logout/', 'opentable.views.user_logout', name='logout'),
    url(r'^register/', 'opentable.views.register_new_user', name='register_new_user'),
    url(r'^changePassword/(?P<user_id>\d+)/$', 'opentable.views.change_password', name='change_password'),
    url(r'^tinymce/', include('tinymce.urls')),

)


if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
    )

players/urls.py
__author__ = 'davidkavanagh'

from django.conf.urls import patterns, url
from players import views

urlpatterns = patterns('',
                       # Examples:
                       url(r'^listPlayers/$', views.list_players, name='list_players'),
                       url(r'^showPlayer/(?P<user_id>\d+)/$', views.show_player, name='show_player'),
                       # url(r'^addplayer/$', views.add_player, name='add_player'),
                       # url(r'^editplayer/(?P<player_id>\d+)/$', views.edit_player, name='edit_player'),
                       # url(r'^deleteplayer/(?P<player_id>\d+)/$', views.delete_player, name='delete_player'),
                       )

writeups/urls.py
__author__ = 'davidkavanagh'

from django.conf.urls import patterns, url
from writeups import views

urlpatterns = patterns('',


    url(r'^listWriteups/$', views.list_writeups, name='list_writeups'),

    #url(r'^archiveWriteupList/(?P<w_month>\w+)/(?P<w_year>\d+)/$', views.archive_list_writeups, name='archive_list_writeups'),

    url(r'^showWriteup/(?P<writeup_id>\d+)/$', views.show_writeup, name='show_writeup'),

    url(r'^addWriteup/$', views.add_writeup, name='add_writeup'),
    url(r'^editWriteup/(?P<writeup_id>\d+)/$', views.add_writeup, name='edit_writeup'),
    url(r'^deleteWriteup/(?P<writeup_id>\d+)/$', views.delete_writeup, name='delete_writeup'),

    url(r'^addComment/(?P<writeup_id>\d+)/$', views.show_writeup, name='add_comment'),
    url(r'^editComment/(?P<writeup_id>\d+)/(?P<comment_id>\d+)/$', views.show_writeup, name='edit_comment'),
    url(r'^deleteComment/(?P<writeup_id>\d+)/(?P<comment_id>\d+)/$', views.delete_comment, name='delete_comment'),

    url(r'^listSummaries/$', views.list_summaries, name='list_summaries'),

    url(r'^archiveSummaryList/(?P<s_month>\w+)/(?P<s_year>\d+)/$',
        views.archive_list_summaries, name='archive_list_summaries'),

    url(r'^characterSummaryList/(?P<character_id>\d+)/$',
        views.character_list_summaries, name='character_list_summaries'),

    url(r'^listPlayerSummaries/(?P<user_id>\d+)/$',
        views.get_summaries_by_player, name='get_summaries_by_player'),

    url(r'^showSummary/(?P<summary_id>\d+)/$', views.show_summary, name='show_summary'),

    url(r'^addSummary/$', views.add_summary, name='add_summary'),
    url(r'^editSummary/(?P<summary_id>\d+)/$', views.add_summary, name='edit_summary'),
    url(r'^deleteSummary/(?P<summary_id>\d+)/$', views.delete_summary, name='delete_summary'),



)

opentable/forms.py
from django import forms
from django.contrib.auth.admin import User, UserCreationForm
from django.contrib.auth.hashers import check_password
from django.db.models import Q


class LoginForm(forms.Form):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'username'
    }), label='')

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'password',
    }), label='')

    class Meta:
        fields = ['username', 'password']

    def is_valid(self):
        """Taken from http://chriskief.com/2012/12/16/override-django-form-is_valid/
            with thanks!!!
        """

        # run the parent validation first
        valid = super(LoginForm, self).is_valid()

        # we're done now if not valid
        if not valid:
            return valid

        # so far so good, get this user based on the username or email
        try:
            user = User.objects.get(
                Q(username=self.cleaned_data['username'])
            )

        # no user with this username or email address
        except User.DoesNotExist:

            self.add_error('username', 'User does not exist')
            return False

        # verify the passwords match
        if not check_password(self.cleaned_data['password'], user.password):
            self.add_error('password', 'incorrect password')
            return False

        # all good
        return True


class CustomUserCreationForm(UserCreationForm):

    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def is_valid(self):
        valid = super(UserCreationForm, self).is_valid()

        if not valid:
            return False

        email = self.cleaned_data['email']

        if len(User.objects.filter(email=email)) > 0:
            self.add_error('email', 'a user with that email already exists')
            return False

        return True

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.set_password(self.cleaned_data['password1'])
        return user


class ChangePasswordForm(forms.Form):

    old_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'password',
        }), label='Old Password')

    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'password',
        }), label='New Password')

    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'password',
        }), label='Confirm New Password')

    class Meta:
        fields = ['old_password', 'new_password1', 'new_password2']

    def is_valid(self, user):

        valid = super(ChangePasswordForm, self).is_valid()

        # we're done now if not valid
        if not valid:
            return valid

        if not check_password(self.cleaned_data['old_password'], user.password):
            self.add_error('old_password', 'incorrect password')
            return False

        if not self.cleaned_data['new_password1'] == self.cleaned_data['new_password2']:
            self.add_error('new_password2', 'passwords do not match')
            return False
        # all good
        return True

opentable/views.py
__author__ = 'David Kavanagh'


from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import RequestContext, render_to_response
from django.core.mail import mail_admins
from django.contrib.auth.decorators import login_required

from characters.models import Character
from writeups.models import Writeup, SessionSummary, Comment
from django.db.models import Count, Sum, Avg
from writeups.models import Writeup, SessionSummary
from opentable.forms import LoginForm, CustomUserCreationForm, ChangePasswordForm

def home(request):

    return render_to_response('opentable/home.html', {}, context_instance=RequestContext(request))


def numbers(request):

    data = {
        'character_count': Character.objects.filter(character_type='PC', hidden=False).count(),
        'writeup_count': Writeup.objects.all().count(),
        'comment_count': Comment.objects.all().count(),
        'summary_count': SessionSummary.objects.all().count(),
        'character_deaths': Character.objects.filter(character_type='PC', hidden=False).aggregate(Sum('num_deaths')),
        'deceased_characters': Character.objects.filter(character_type='PC', hidden=False, deceased=True).count(),
        'races': Character.objects.filter(character_type='PC', hidden=False).values('race').annotate(the_count=Count('race')),
        'classes': Character.objects.filter(character_type='PC', hidden=False).values('character_class').annotate(the_count=Count('character_class')),
        'writeups_per_player': User.objects.annotate(Count('writeup')),
        'party_level': Character.objects.filter(character_type='PC', hidden=False).values('level').aggregate(Sum('level'), Avg('level')),
    }

    return render_to_response('opentable/numbers.html', data, context_instance=RequestContext(request))

def about(request):

    return render_to_response('opentable/about.html', {}, context_instance=RequestContext(request))

def user_login(request):

    login_form = LoginForm()

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        login_form = LoginForm(request.POST)

        if login_form.is_valid():

            user = authenticate(username=username, password=password)

            if user:
                if user.is_active:
                    login(request, user)
                    redirect_path = request.GET['next']
                    return HttpResponseRedirect(redirect_path)
                else:
                    login_form.add_error(None, "Your account has not yet been activated.")

    if 'next' in request.GET.keys():
        next_page = request.GET['next']
    else:
        next_page = '/'

    return render_to_response('opentable/login.html',
                              {'login_form': login_form, 'next_page': next_page},
                              context_instance=RequestContext(request))


def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')


def register_new_user(request):

    new_user_form = CustomUserCreationForm()

    if request.method == 'POST':
        new_user_form = CustomUserCreationForm(request.POST)

        if new_user_form.is_valid():
            new_user = new_user_form.save(commit=False)
            new_user.is_active = False
            new_user.save()


            email_subject = u'Ptolus Open Table - New User'

            email_msg = u"""
            A new user has registered to the ptolus open table site.
            Please review their details and activate them if approved.
            """

            mail_admins(email_subject, email_msg, fail_silently=False)

            return HttpResponseRedirect('/')

    data = {'new_user_form': new_user_form}

    return render_to_response('opentable/register.html', data, context_instance=RequestContext(request))

@login_required
def change_password(request, user_id):

    this_user = User.objects.get(pk=user_id)
    if request.method == 'POST':
        change_password_form = ChangePasswordForm(request.POST)

        if change_password_form.is_valid(this_user):
            this_user.set_password(change_password_form.cleaned_data['new_password1'])
            this_user.save()
            redirect_url = '/players/showPlayer/{0}/'.format(this_user.id)

            return HttpResponseRedirect(redirect_url)
    else:
        change_password_form = ChangePasswordForm()

    print change_password_form.fields

    data = {'change_password_form': change_password_form}

    return render_to_response('opentable/change_password.html', data, context_instance=RequestContext(request))


def get_writeup_archive():
    archive_dates = Writeup.objects.datetimes('date_added', 'month', order='DESC')
    return archive_dates


def get_summary_archive():
    archive_dates = SessionSummary.objects.datetimes('date_added', 'month', order='DESC')
    return archive_dates


def is_gm(user):
    """
    callback function for checking is user is gm and therefore allowed to add SessionSummary
    """
    if not user.is_anonymous():
        if u'gms' in [g.name for g in User.objects.get(pk=user.id).groups.all()]:
            return True

    return False

templates/opentable/about.html
{% extends 'opentable/base.html' %}

{% block content %}
<div>
   <p>The ptolus open table project is a gaming group run by me (Davy), and a friend who won't be named because
        he values his web anonymity. We've been running a free form DnD game using the Pathfinder rule set for about
        15 people (8 - 9 of whom are regulars) for almost a year now.</p>

    <p>We've had a lot of laughs, some great characters and hopefully learned a few things about being a good GM or player
        along the way. This site is a way to keep track of all the characters that are active within the games as well as their
        write ups after each game and GM summaries for the games. It's also a test-bed for me improving my web-dev skills.</p>

    <p>The open table format of gaming is one we stumbled across and described (probably in better detail) <a href="http://thealexandrian.net/wordpress/1223/roleplaying-games/opening-your-game-table">here</a>.
        Essentially, there are no set times for games. A participator decides to run a game, and sends an email with the time of this game.
        Players, drawn from a larger pool of participants, respond yay or nay. These are now the players for this game. This idea of a fluid
        set of players has an important knock-on effect. At the end of every game, the GM must end the game "back in town". In other words -
        the GM shouldn't trap the party underground, unless (s)he plans to kill them outright.</p>

    <p> How we've implemented the open table is that we have a pool of GMs and a pool of players. The campaign is set in ptolus, and the characters
        are all members of the delvers guild. The GMs insert their various adventures, games, dungeons, and the like, into the ptolus setting,
        and then we alternate between different GMs (and therefore, dungeons). <p>

    <p>The idea of no fixed day/time for games, and the fluid player/character composition of the group means that, on average we've gotten a lot more gaming done,
        with much fewer cancelled games, since there are usually always at least three people to play.</p>

    <p> We play over the internet using google hangouts and a free piece of software called <a href="http://www.rptools.net/toolbox/maptool/">maptool</a>, which allows visualisation of the characters,
        the enemies, the terrain and their relative positions to one another. </p>

</div>



{% endblock %}

templates/opentable/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load url from future %}
{% load crispy_forms_tags %}
{% load humanize %}
{% load opentable_extras %}
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>

    <link href="{{STATIC_URL}}/css/bootstrap.darkly.css" rel="stylesheet" type="text/css">
    <!--<link href="{{STATIC_URL}}/css/bootstrap.css" rel="stylesheet" type="text/css">-->
    <link href="{{STATIC_URL}}/css/davy-custom.css" rel="stylesheet" type="text/css">
    <link href="{{STATIC_URL}}/css/bootstrap-datetimepicker.min.css" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{{STATIC_URL}}/js/highcharts/highcharts.js"></script>
    <script src="{{STATIC_URL}}/js/moment.min.js"></script>
    <script src="{{STATIC_URL}}/js/bootstrap-datetimepicker.min.js"></script>

    <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>-->

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-62758309-1', 'auto');
      ga('send', 'pageview');

    </script>


    <script type="text/javascript">
        $(document).ready(function(){
            $('[data-toggle="tooltip"]').tooltip({
                placement : 'top'
            });
        });
    </script>

    {% block custom_header_scripts %}

    {% endblock %}


</head>
    <body>


        <nav class="navbar navbar-default navbar-fixed-top">

            <div class="container-fluid">

                <div class="navbar-header">

                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    {% if not user.is_authenticated %}
                    <a type="button" class="navbar-toggle collapsed" aria-expanded="false" aria-controls="navbar" href="{% url 'login' %}?next={{request.path}}">
                        login/register
                    </a>
                    {% endif %}
                    <a class="navbar-brand" href="{% url 'home' %}">Ptolus Open Table</a>

                </div>

                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">

                        <li><a href="{% url 'numbers' %}">Data</a></li>
                        <li><a href="{% url 'about' %}">About</a></li>

                        <li role="presentation" class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">List<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{% url 'campaigns:list_campaigns' %}">Campaigns</a></li>
                                <li><a href="{% url 'characters:list_characters' %}">Characters</a></li>
                                <li><a href="{% url 'writeups:list_writeups' %}">Write Ups</a></li>
                                <li><a href="{% url 'writeups:list_summaries' %}">Summaries</a></li>
                                <li><a href="{% url 'players:list_players' %}">Players</a></li>
                            </ul>
                        </li>
                        <li role="presentation" class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">Add<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{% url 'campaigns:add_campaign' %}">Campaign</a></li>
                                <li><a href="{% url 'characters:add_character' %}">Character</a></li>
                                <li><a href="{% url 'writeups:add_writeup' %}">Write Up</a></li>
                                {% if request.user|has_group:"gms" %}
                                    <li><a href="{% url 'writeups:add_summary' %}">Summary</a></li>
                                {% endif %}
                            </ul>
                        </li>

                    {% if user.is_authenticated and user.is_superuser %}
                        <li><a href="/admin/">Admin</a></li>
                    {% endif %}
                    </ul>

                    {% if user.is_authenticated %}
                        <ul class="nav navbar-nav navbar-right">
                            <li><a class="active" href="{% url 'players:show_player' user.id %}">Welcome {{ user.username|capfirst }} </a></li>
                            <li><a href='{% url "logout" %}'>Logout</a></li>
                        </ul>
                    {% else %}

                    <!--<form class="nav navbar-nav navbar-form navbar-right" id="login_form" method="POST" action='{% url "login" %}?next={{request.path}}'>-->


                    <form class="navbar-form navbar-right navbar-collapse collapse" id="login_form" method="POST" action='{% url "login" %}?next={{request.path}}'>
                            {% csrf_token %}
                            {{navbar_login_form.username}}
                            {{navbar_login_form.password}}

                            <!--<div class="form-group">
                            <input type="text" class="form-control", name="username" placeholder="username">
                            <input type="password" class="form-control" name="password" placeholder="password">
                            </div>-->
                            <button type="submit" class="btn btn-primary">Login</button>
                            <a href='{% url "register_new_user" %}' class="btn btn-primary">Register</a>
                        </form>
                    {% endif %}
                </div><!--/.nav-collapse -->
            </div><!--/.container-fluid -->
        </nav>



        <div class="container-fluid">

            <div class="col-xs-9">
                {% block content %}

                {% endblock %}
            </div>

            <div class="col-xs-3">
                <div class="panel panel-default">
                <div class="panel-heading">Recent Items:</div>
                    <div class="panel-body">
                        <ul class="list-group">
                            {% for type, url_string, item in recent_items %}


                                {% if type == 'comment' %}
                                    <li class="list-group-item"><a href="{% url url_string item.writeup.id %}">new {{type}} - {{item}}</a>
                                        <span class="comment-meta">{{item.date_added|naturaltime}}</span></li>
                                {% else %}
                                    <li class="list-group-item"><a href="{% url url_string item.id %}">new {{type}} - {{item}}</a>
                                        <span class="comment-meta">{{item.date_added|naturaltime}}</span></li>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>





                 <!---
                 <nav>
                     <ul class="nav nav-pills nav-stacked">
                        <li><h4><a href="{% url 'characters:list_characters' %}">Characters</a></h4></li>
                         {% for this_character in recently_added_characters %}
                            <li><a href="{% url 'characters:show_character' this_character.id %}">{{this_character.name}}</a></li>
                         {% endfor %}
                        <li><h4><a href="{% url 'writeups:list_writeups' %}">Write Ups</a></h4></li>
                        {% for w_date in writeup_archive %}
                            <li><a href="{% url 'writeups:archive_list_writeups' w_date|date:'m' w_date|date:'Y'  %}">{{w_date|date:"F, Y"}}</a></li>
                        {% endfor %}

                        <li><h4><a href="{% url 'writeups:list_summaries' %}">Session Summaries</a></h4></li>
                        {% for s_date in summary_archive %}
                            <li><a href="{% url 'writeups:archive_list_summaries' s_date|date:'m' s_date|date:'Y' %}">{{s_date|date:"F, Y"}}</a></li>
                        {% endfor %}
                    </ul>
                </nav>
                -->

        </div><!--/.container-fluid-->

        <script type="text/javascript" src="{{ STATIC_URL }}js/tinymce/tinymce.min.js"></script>
        <script type="text/javascript" src="{% url 'tinymce-js' 'NAME' %}" ></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="{{STATIC_URL}}/js/bootstrap.min.js"></script>
        <script src="{{STATIC_URL}}/js/custom.js"></script>

    </body>
</html>

templates/opentable/home.html
{% extends 'opentable/base.html' %}

{% block content %}

    <div class="jumbotron">
    <h4>Welcome to the Ptolus Open Table Project!</h4>
    </div>
    <p>
        Within these dark pages, lie the tales of long forgotten heroes, the songs of powerful men and women.
        Be warned, traveler, for this tome is not for the faint of heart. Only the brave or bold, may
        journey forth unchanged.
    </p>

    <div class="container-fluid">
        <div class="col-xs-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading"><h6>Campaigns</h6></div>
                <div class="panel-body">
                    <p>View the past and currently tracked campiagns or add a new one!</p>

                    <div class="btn-group margins-10">
                        <a href="{% url 'campaigns:list_campaigns' %}" type="button" class="btn btn-default" aria-label="list" data-toggle="tooltip" data-original-title="List">
                            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                        </a>
                        <a href="{% url 'campaigns:add_campaign' %}" type="button" class="btn btn-default" aria-label="Add" data-toggle="tooltip" data-original-title="Add">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xs-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading"><h6>Characters</h6></div>
                    <div class="panel-body">
                        <p>View the characters from all the campaigns, read their back-stories and stats or add your own character. </p>

                    <div class="btn-group margins-10">
                        <a href="{% url 'characters:list_characters' %}" type="button" class="btn btn-default" aria-label="list" data-toggle="tooltip" data-original-title="List">
                            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                        </a>
                        <a href="{% url 'characters:add_character' %}" type="button" class="btn btn-default" aria-label="Add" data-toggle="tooltip" data-original-title="Add">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading"><h6>Sessions</h6></div>
                    <div class="panel-body">
                         <p>View all game sessions that have been played and what characters played in them. You can add a new session summary as well </p>

                    <div class="btn-group margins-10">
                        <a href="{% url 'writeups:list_summaries' %}" type="button" class="btn btn-default" aria-label="list" data-toggle="tooltip" data-original-title="List">
                            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                        </a>
                        <a href="{% url 'writeups:add_summary' %}" type="button" class="btn btn-default" aria-label="Add" data-toggle="tooltip" data-original-title="Add">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading"><h6>Write Ups</h6></div>
                    <div class="panel-body">
                        <p>Read and comment on previous write ups, or add a new one for one of your characters.</p>

                    <div class="btn-group margins-10">
                        <a href="{% url 'writeups:list_writeups' %}" type="button" class="btn btn-default" aria-label="list" data-toggle="tooltip" data-original-title="List">
                            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                        </a>
                        <a href="{% url 'writeups:add_writeup' %}" type="button" class="btn btn-default" aria-label="Add" data-toggle="tooltip" data-original-title="Add">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading"><h6>Players</h6></div>
                    <div class="panel-body">
                        <p>See a list of all players, links to their characters, write ups and session summaries, or register for an account.</p>

                    <div class="btn-group margins-10">
                        <a href=" {% url 'players:list_players' %}" type="button" class="btn btn-default" aria-label="list" data-toggle="tooltip" data-original-title="List">
                            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                        </a>
                        <a href="{% url 'register_new_user' %}" type="button" class="btn btn-default" aria-label="Add" data-toggle="tooltip" data-original-title="Add">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}