campaigns/urls.py
__author__ = 'davidkavanagh'

from django.conf.urls import patterns, url
from campaigns import views

urlpatterns = patterns('',
    # Examples:
    url(r'^$', views.list_campaigns, name='list_campaigns'),
    url(r'^listCampaigns/$', views.list_campaigns, name='list_campaigns'),
    url(r'^showCampaign/(?P<campaign_id>\d+)/$', views.show_campaign, name='show_campaign'),
    url(r'^addCampaign/$', views.add_campaign, name='add_campaign'),
    url(r'^editCampaign/(?P<campaign_id>\d+)/$', views.add_campaign, name='edit_campaign'),
    url(r'^deleteCampaign/(?P<campaign_id>\d+)/$', views.delete_campaign, name='delete_campaign'),
)

opentable/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from opentable import views

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'opentable.views.home', name='home'),
    url(r'^', include('characters.urls', namespace='characters')),
    url(r'^writeups/', include('writeups.urls', namespace='writeups')),
    url(r'^campaigns/', include('campaigns.urls', namespace='campaigns')),
    url(r'^players/', include('players.urls', namespace='players')),
    url(r'^numbers/', 'opentable.views.numbers', name='numbers'),
    url(r'^about/', 'opentable.views.about', name='about'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', 'opentable.views.user_login', name='login'),
    url(r'^logout/', 'opentable.views.user_logout', name='logout'),
    url(r'^register/', 'opentable.views.register_new_user', name='register_new_user'),
    url(r'^changePassword/(?P<user_id>\d+)/$', 'opentable.views.change_password', name='change_password'),
    url(r'^tinymce/', include('tinymce.urls')),

)


if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
    )

players/urls.py
__author__ = 'davidkavanagh'

from django.conf.urls import patterns, url
from players import views

urlpatterns = patterns('',
                       # Examples:
                       url(r'^listPlayers/$', views.list_players, name='list_players'),
                       url(r'^showPlayer/(?P<user_id>\d+)/$', views.show_player, name='show_player'),
                       # url(r'^addplayer/$', views.add_player, name='add_player'),
                       # url(r'^editplayer/(?P<player_id>\d+)/$', views.edit_player, name='edit_player'),
                       # url(r'^deleteplayer/(?P<player_id>\d+)/$', views.delete_player, name='delete_player'),
                       )

campaigns/models.py
from django.db import models
# Create your models here.


class Campaign(models.Model):

    name = models.CharField(max_length=50)

    rule_set = models.CharField(max_length=100, verbose_name='System (version)')

    description = models.TextField()

    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_added',)

    def __unicode__(self):
        return self.name

campaigns/forms.py
__author__ = 'davidkavanagh'

from campaigns.models import Campaign
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout
from crispy_forms.bootstrap import InlineField
from django import forms



class CampaignForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(CampaignForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'bootstrap3'
        self.helper.form_method = 'POST'
        self.helper.form_action = "/campaigns/addCampaign/"

        self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = Campaign
        fields = ['name', 'rule_set', 'description']

campaigns/views.py
from django.http import request
from django.shortcuts import HttpResponseRedirect, RequestContext, render_to_response
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from campaigns.models import Campaign
from campaigns.forms import CampaignForm

# Create your views here.


def list_campaigns(request):

    page = request.GET.get('page')

    campaigns_queryset = Campaign.objects.all()

    paginator = Paginator(campaigns_queryset, 10)

    pages = [i+1 for i in range(paginator.num_pages)]

    try:
        campaigns = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        campaigns = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        campaigns = paginator.page(paginator.num_pages)

    data = {'campaigns': campaigns}

    return render_to_response('campaigns/list_campaign.html', data, context_instance=RequestContext(request))


def show_campaign(request,campaign_id):

    this_campaign = Campaign.objects.get(pk=campaign_id)

    data = {'this_campaign': this_campaign}

    return render_to_response('campaigns/show_campaign.html', data, context_instance=RequestContext(request))

@login_required
def add_campaign(request, campaign_id=None):

    if campaign_id is not None:
        this_campaign = Campaign.objects.get(pk=campaign_id)
    else:
        this_campaign = None

    if request.method == "POST":

        campaign_form = CampaignForm(request.POST, instance=this_campaign)

        if campaign_form.is_valid():
            save_it = campaign_form.save(commit=False)
            save_it.save()

            this_campaign = Campaign.objects.order_by('-submission_date')[0]
            redirect_to_url = '/campaigns/showCampaign/{0}/'.format(this_campaign.id)

            return HttpResponseRedirect(redirect_to_url)

    else:
        campaign_form = CampaignForm(instance=this_campaign)

    if campaign_id is not None:
        campaign_form.helper.form_action = '/campaigns/editCampaign/' + campaign_id + '/'

    data = {'campaign_form': campaign_form}
    return render_to_response('campaigns/add_campaign.html', data, context_instance=RequestContext(request))


def delete_campaign(request, campaign_id):

    this_campaign = Campaign.objects.get(pk=campaign_id)

    this_campaign.delete()

    return HttpResponseRedirect('/campaigns/listCampaigns/')

templates/campaigns/addCampaign.html
{% extends 'opentable/base.html' %}


{% block content %}

{% load crispy_forms_tags %}
    <div class="row">
    <h3>Enter Campaign Details:</h3>
            {% crispy campaign_form campaign_form.helper %}
    </div>

    <p></p>



{% endblock %}

templates/campaigns/add_campaign.html
{% extends 'opentable/base.html' %}


{% block content %}

{% load crispy_forms_tags %}
    <div class="row">
    <h3>Enter Campaign Details:</h3>
            {% crispy campaign_form campaign_form.helper %}
    </div>

    <p></p>



{% endblock %}

templates/campaigns/index_campaign.html
{% extends 'opentable/base.html' %}


{% block content %}


    <ul class="pagination">
    {% if campaigns.has_previous %}
    <li><a href="?page={{ campaigns.previous_page_number }}">Back</a></li>
    {% else %}
        <li class="disabled"><a href="#">Back</a></li>
    {% endif %}



        {% for p in pages %}

        {% if p == campaigns.number %}
            <li class="active"><a href="#">{{ campaigns.number }}</a></li>
        {% else %}
            <li><a href="?page={{ p }}">{{ p }}</a></li>
        {% endif %}

        {% endfor %}


    {% if campaigns.has_next %}
       <li><a href="?page={{ campaigns.next_page_number }}">Next</a></li>
    {% else %}
        <li class="disabled"><a href="#">Next</a></li>
    {% endif %}
    </ul>

    <div class="writeups-list">
        {% for campaign in campaigns %}
            <div class="writeup-short">
                <a href="{% url 'campaigns:show_campaign' campaign.id %}"><h4>{{campaign.name}}</h4></a>
                <h6 class="writeup-meta">running since {{campaign.date_added}}</h6>
                <div class="writeup-short-body">
                    {{campaign.description|truncatechars_html:200|safe}}
                </div>
            </div>

        {% empty %}



            <h3>Ooops!</h3>
            <p>No write ups here yet.</p>

    {% endfor %}
    </div>




{% endblock %}

templates/campaigns/list_campaign.html
{% extends 'opentable/base.html' %}


{% block content %}


    <ul class="pagination">
    {% if campaigns.has_previous %}
    <li><a href="?page={{ campaigns.previous_page_number }}">Back</a></li>
    {% else %}
        <li class="disabled"><a href="#">Back</a></li>
    {% endif %}



        {% for p in pages %}

        {% if p == campaigns.number %}
            <li class="active"><a href="#">{{ campaigns.number }}</a></li>
        {% else %}
            <li><a href="?page={{ p }}">{{ p }}</a></li>
        {% endif %}

        {% endfor %}


    {% if campaigns.has_next %}
       <li><a href="?page={{ campaigns.next_page_number }}">Next</a></li>
    {% else %}
        <li class="disabled"><a href="#">Next</a></li>
    {% endif %}
    </ul>

    <div class="writeups-list">
        {% for campaign in campaigns %}
            <div class="writeup-short">
                <a href="{% url 'campaigns:show_campaign' campaign.id %}"><h4>{{campaign.name}}</h4></a>
                <h6 class="writeup-meta">running since {{campaign.date_added}}</h6>
                <div class="writeup-short-body">
                    {{campaign.description|truncatechars_html:200|safe}}
                </div>
            </div>

        {% empty %}

            <h3>Ooops!</h3>
            <p>No Campaigns here yet.</p>

    {% endfor %}
    </div>




{% endblock %}

templates/campaigns/show_campaign.html
{% extends 'opentable/base.html' %}


{% block content %}


    <div class="panel panel-default writeup-box">
        <div class="gear-menu">
            {% if user.is_authenticated and user.is_superuser%}
                    <div class="btn-group" role="group">
                        <a href="{% url 'campaigns:edit_campaign' this_campaign.id %}" type="button" class="btn btn-default btn-sm" aria-label="edit" data-toggle="tooltip" data-original-title="Edit">
                            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                        </a>

                        <a href="{% url 'campaigns:delete_campaign' this_campaign.id  %}" type="button" class="btn btn-default btn-sm" aria-label="delete" data-toggle="tooltip" data-original-title="Delete">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </a>
                    </div>
            {% endif %}
        </div>

        <h3>{{this_campaign.name}}</h3>
        <h6 class="writeup-meta">running since {{this_campaign.date_added}}</h6>

        <div class="writeup-text">
            {{this_campaign.description|safe}}
        </div>
    </div>



{% endblock %}