opentable/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from opentable import views

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'opentable.views.home', name='home'),
    url(r'^', include('characters.urls', namespace='characters')),
    url(r'^writeups/', include('writeups.urls', namespace='writeups')),
    url(r'^campaigns/', include('campaigns.urls', namespace='campaigns')),
    url(r'^players/', include('players.urls', namespace='players')),
    url(r'^numbers/', 'opentable.views.numbers', name='numbers'),
    url(r'^about/', 'opentable.views.about', name='about'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', 'opentable.views.user_login', name='login'),
    url(r'^logout/', 'opentable.views.user_logout', name='logout'),
    url(r'^register/', 'opentable.views.register_new_user', name='register_new_user'),
    url(r'^changePassword/(?P<user_id>\d+)/$', 'opentable.views.change_password', name='change_password'),
    url(r'^tinymce/', include('tinymce.urls')),

)


if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
    )

players/urls.py
__author__ = 'davidkavanagh'

from django.conf.urls import patterns, url
from players import views

urlpatterns = patterns('',
                       # Examples:
                       url(r'^listPlayers/$', views.list_players, name='list_players'),
                       url(r'^showPlayer/(?P<user_id>\d+)/$', views.show_player, name='show_player'),
                       # url(r'^addplayer/$', views.add_player, name='add_player'),
                       # url(r'^editplayer/(?P<player_id>\d+)/$', views.edit_player, name='edit_player'),
                       # url(r'^deleteplayer/(?P<player_id>\d+)/$', views.delete_player, name='delete_player'),
                       )

writeups/urls.py
__author__ = 'davidkavanagh'

from django.conf.urls import patterns, url
from writeups import views

urlpatterns = patterns('',


    url(r'^listWriteups/$', views.list_writeups, name='list_writeups'),

    #url(r'^archiveWriteupList/(?P<w_month>\w+)/(?P<w_year>\d+)/$', views.archive_list_writeups, name='archive_list_writeups'),

    url(r'^showWriteup/(?P<writeup_id>\d+)/$', views.show_writeup, name='show_writeup'),

    url(r'^addWriteup/$', views.add_writeup, name='add_writeup'),
    url(r'^editWriteup/(?P<writeup_id>\d+)/$', views.add_writeup, name='edit_writeup'),
    url(r'^deleteWriteup/(?P<writeup_id>\d+)/$', views.delete_writeup, name='delete_writeup'),

    url(r'^addComment/(?P<writeup_id>\d+)/$', views.show_writeup, name='add_comment'),
    url(r'^editComment/(?P<writeup_id>\d+)/(?P<comment_id>\d+)/$', views.show_writeup, name='edit_comment'),
    url(r'^deleteComment/(?P<writeup_id>\d+)/(?P<comment_id>\d+)/$', views.delete_comment, name='delete_comment'),

    url(r'^listSummaries/$', views.list_summaries, name='list_summaries'),

    url(r'^archiveSummaryList/(?P<s_month>\w+)/(?P<s_year>\d+)/$',
        views.archive_list_summaries, name='archive_list_summaries'),

    url(r'^characterSummaryList/(?P<character_id>\d+)/$',
        views.character_list_summaries, name='character_list_summaries'),

    url(r'^listPlayerSummaries/(?P<user_id>\d+)/$',
        views.get_summaries_by_player, name='get_summaries_by_player'),

    url(r'^showSummary/(?P<summary_id>\d+)/$', views.show_summary, name='show_summary'),

    url(r'^addSummary/$', views.add_summary, name='add_summary'),
    url(r'^editSummary/(?P<summary_id>\d+)/$', views.add_summary, name='edit_summary'),
    url(r'^deleteSummary/(?P<summary_id>\d+)/$', views.delete_summary, name='delete_summary'),



)

writeups/models.py
__author__ = 'davidkavanagh'

from django.db import models
from django.contrib.auth.models import User
from characters.models import Character
from django.utils import timezone

# Create your models here.


class Writeup(models.Model):

    author = models.ForeignKey(User)

    author_character = models.ForeignKey(Character, default=1)

    date_added = models.DateTimeField(default=timezone.now)

    last_edited = models.DateTimeField(auto_now_add=False, auto_now=True)

    post_content = models.TextField()

    class Meta:
        ordering = ('-date_added',)
        verbose_name = 'Write Up'

    def __unicode__(self):
        return ' by {0}'.format(self.author_character)


class Comment(models.Model):

    author = models.ForeignKey(User)

    writeup = models.ForeignKey(Writeup, default=1)

    date_added = models.DateTimeField(auto_now_add=True, blank=True)

    last_edited = models.DateTimeField(auto_now_add=False, auto_now=True)

    comment_content = models.TextField(max_length=200)

    def __unicode__(self):
            return 'comment by {0}'.format(self.author)


class SessionSummary(models.Model):

    gm = models.ForeignKey(User)

    number = models.IntegerField()

    location = models.CharField(max_length=500)

    session_characters = models.ManyToManyField(Character)

    xp_awarded = models.IntegerField()

    summary_content = models.TextField()

    important_npcs = models.CharField(max_length=500)

    date_added = models.DateTimeField(default=timezone.now, verbose_name='Session Date (eg. YYYY-DD-MM 00:00:00)')

    class Meta:
        ordering = ('-date_added',)
        verbose_name = 'Session Summary'

    def __unicode__(self):
        return 'Session {0}'.format(self.number)

writeups/views.py
import calendar
import datetime


from django.shortcuts import render_to_response, RequestContext
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models import Q

from opentable.views import is_gm
from writeups.models import Writeup, Comment, SessionSummary
from writeups.forms import WriteupForm, CommentForm, SummaryForm, WriteupSearchForm
from characters.models import Character


########################################################################################################################
# Writeup Views
########################################################################################################################

def list_writeups(request):
    """
    Paginated lists of writeups.
    """

    page = request.GET.get('page')

    writeup_queryset = Writeup.objects.all()

    if request.method == 'GET':
        search_player = request.GET.get('player', None)
        search_character = request.GET.get('character', None)
        search_text = request.GET.get('search_text', None)
        search_start_date = request.GET.get('date_range_start', None)
        search_end_date = request.GET.get('date_range_end', None)
        search_sort = request.GET.get('sort_by', None)

        if search_player:
            writeup_queryset = writeup_queryset.filter(author__pk=search_player)

        if search_character:
            writeup_queryset = writeup_queryset.filter(author_character__pk=search_character)

        if search_text:
            writeup_queryset = writeup_queryset.filter(post_content__icontains=search_text)

        if search_start_date:
            writeup_queryset = writeup_queryset.filter(date_added__gte=search_start_date)

        if search_end_date:
            writeup_queryset = writeup_queryset.filter(date_added__lte=search_end_date)

        if search_sort == 'O':
            writeup_queryset = writeup_queryset.order_by('date_added')

        search_form = WriteupSearchForm(request.GET)

    else:
        search_form = WriteupSearchForm()

    paginator = Paginator(writeup_queryset, 10)

    pages = [i+1 for i in range(paginator.num_pages)]

    try:
        writeups = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        writeups = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        writeups = paginator.page(paginator.num_pages)

    if not is_gm(request.user):
        search_form.fields['character'].choices = [('', '---------')] + [(c.id, str(c)) for c in Character.objects.filter(hidden=False)]

    data = {'writeups': writeups, 'pages': pages, 'search_form': search_form}

    return render_to_response('writeups/list_writeups.html', data, context_instance=RequestContext(request))

"""
# function not currently used. Keeping as I may add it back in later

def archive_list_writeups(request, w_month, w_year):
    year = int(w_year)
    month = int(w_month)
    month_range = calendar.monthrange(year, month)
    start = datetime.datetime(year=year, month=month, day=1)
    end = datetime.datetime(year=year, month=month, day=month_range[1])

    writeup_queryset = Writeup.objects.filter(submission_date__range=(start.date(), end.date()))
    return list_writeups(request)
"""


def show_writeup(request, writeup_id, comment_id=None):

    this_writeup = Writeup.objects.get(pk=writeup_id)
    this_writeup_comments = Comment.objects.filter(writeup__id=writeup_id).order_by('date_added')
    
    if comment_id is not None:
        this_comment = Comment.objects.get(pk=comment_id)

    if request.method == "POST":
        if comment_id is not None:
            comment_form = CommentForm(request.POST, instance=this_comment)
        else:
            comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
                save_it = comment_form.save(commit=False)
                save_it.author = request.user
                save_it.writeup = this_writeup #why did I do this?
                save_it.save()

                redirect_to_url = '/writeups/showWriteup/' + writeup_id + '/'
                return HttpResponseRedirect(redirect_to_url)
    else:
        if comment_id is not None:
            comment_form = CommentForm(instance=this_comment)
        else:
            comment_form = CommentForm(None)

    comment_form.helper.form_action = '/writeups/addComment/' + writeup_id + '/'

    if comment_id is not None:
        comment_form.helper.form_action = '/writeups/editComment/' + writeup_id + '/' + comment_id + '/'

    data = {'this_writeup': this_writeup, 'this_writeup_comments': this_writeup_comments}

    if request.user.is_authenticated():
        data['comment_form'] = comment_form

    next_writeup = Writeup.objects.filter(date_added__gt=this_writeup.date_added).last()
    previous_writeup = Writeup.objects.filter(date_added__lt=this_writeup.date_added).first()

    data['next_writeup'] = next_writeup
    data['previous_writeup'] = previous_writeup

    return render_to_response('writeups/show_writeup.html', data, context_instance=RequestContext(request))


@login_required
def add_writeup(request, writeup_id=None):
    
    if writeup_id is not None:
        this_writeup = Writeup.objects.get(pk=writeup_id)

    if request.method == "POST":
        if writeup_id is not None:
            writeup_form = WriteupForm(request.POST,  instance=this_writeup)

        else:
            writeup_form = WriteupForm(request.POST)

        if writeup_form.is_valid():
            save_it = writeup_form.save(commit=False)
            save_it.save()

            this_writeup = Writeup.objects.order_by('-last_edited')[0]
            redirect_to_url = '/writeups/showWriteup/{0}/'.format(this_writeup.id)

            return HttpResponseRedirect(redirect_to_url)

    else:
        if writeup_id is not None:
            writeup_form = WriteupForm(instance=this_writeup)

        else:
            writeup_form = WriteupForm()
            writeup_form.initial['author'] = request.user

    if writeup_id is not None:
        writeup_form.helper.form_action = '/writeups/editWriteup/' + writeup_id + '/'

    if not request.user.is_superuser:
            writeup_form.fields['author'].choices = [(request.user.id, str(request.user))]
            author_characters = [(c.id, str(c)) for c in Character.objects.filter(player__pk=request.user.id)]
            writeup_form.fields['author_character'].choices = author_characters


    data = {'writeup_form': writeup_form}

    return render_to_response('writeups/add_writeup.html', data, context_instance=RequestContext(request))


def delete_writeup(request, writeup_id):

    this_writeup = Writeup.objects.get(pk=writeup_id)
    this_writeup.delete()

    return HttpResponseRedirect('/writeups/listWriteups/')

########################################################################################################################
# Comment Views
########################################################################################################################
@login_required
def add_comment(request, writeup_id, comment_id=None):
    """ The logic of adding the comment to the DB is handled in show writeup
    """
    data = {}
    url_to_render = '/writeups/showWriteup/' + writeup_id + '/'

    return render_to_response(url_to_render, data, context_instance=RequestContext(request))


def delete_comment(request, writeup_id, comment_id):
    this_comment = Comment.objects.get(pk=comment_id)
    this_comment.delete()
    redirect_url = '/writeups/showWriteup/' + writeup_id + '/'
    return HttpResponseRedirect(redirect_url)


########################################################################################################################
# SessionSummary Views
########################################################################################################################


def list_summaries(request, query_set=None):
    """
    View the most 5 recently submitted session along with number of comments in paginated view.
    """
    page = request.GET.get('page')

    if query_set is None:
        summary_queryset = SessionSummary.objects.all()
    else:
        summary_queryset = query_set

    paginator = Paginator(summary_queryset, 10)

    pages = [i+1 for i in range(paginator.num_pages)]

    try:
        summaries = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        summaries = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        summaries = paginator.page(paginator.num_pages)

    data = {'summaries': summaries, 'pages': pages}

    return render_to_response('writeups/list_summaries.html', data, context_instance=RequestContext(request))


def archive_list_summaries(request, s_month, s_year):

    year = int(s_year)
    month = int(s_month)
    month_range = calendar.monthrange(year, month)
    start = datetime.datetime(year=year, month=month, day=1)
    end = datetime.datetime(year=year, month=month, day=month_range[1])

    summary_queryset = SessionSummary.objects.filter(session_date__range=(start.date(), end.date()))
    return list_summaries(request, query_set=summary_queryset)


def character_list_summaries(request, character_id):
    summary_queryset = SessionSummary.objects.filter(session_characters__pk=character_id)
    return list_summaries(request, query_set=summary_queryset)


def show_summary(request, summary_id):
    this_summary = SessionSummary.objects.get(pk=summary_id)
    data = {'this_summary': this_summary}
    return render_to_response('writeups/show_summary.html', data, context_instance=RequestContext(request))


@login_required
@user_passes_test(is_gm, login_url='/writeups/listSummaries/')

templates/writeups/add_summary.html
{% extends 'opentable/base.html' %}


{% block content %}

{% load crispy_forms_tags %}
    <div class="row">
    <h3>Enter Summary Details:</h3>
             {% crispy summary_form summary_form.helper %}
    </div>



{% endblock %}

templates/writeups/add_writeup.html
{% extends 'opentable/base.html' %}


{% block content %}

{% load crispy_forms_tags %}
    <div class="row">
    <h3>Enter Character Details:</h3>
            {% crispy writeup_form writeup_form.helper %}
    </div>



{% endblock %}

templates/writeups/index_summaries.html
{% extends 'opentable/base.html' %}

{% block content %}

  <ul class="pagination">
    {% if summaries.has_previous %}
    <li><a href="?page={{ writeups.previous_page_number }}">Back</a></li>
    {% else %}
        <li class="disabled"><a href="#">Back</a></li>
    {% endif %}

        {% for p in pages %}

        {% if p == summaries.number %}
            <li class="active"><a href="#">{{ summaries.number }}</a></li>
        {% else %}
            <li><a href="?page={{ p }}">{{ p }}</a></li>
        {% endif %}

        {% endfor %}

    {% if summaries.has_next %}
       <li><a href="?page={{ writeups.next_page_number }}">Next</a></li>
    {% else %}
        <li class="disabled"><a href="#">Next</a></li>
    {% endif %}
    </ul>

    <div class="writeups-list">
        {% for summary in summaries %}
                <div class="writeup-short">
                    <a href="{% url 'writeups:show_summary' summary.id %}"><h4>Session {{summary.number}}</h4></a>
                    <h6 class="writeup-meta">by {{summary.gm}} on {{summary.date_added}}</h6>
                    <h5>{{summary.location}}</h5>
                    <ul class="list-inline">
                    {% for char in summary.session_characters.all %}
                        <!-- TODO: make these links to character stats pages - with tool tips! -->
                        <li><img class="character-token-small" src="{{MEDIA_URL}}/{{char.character_token}}"></li>
                    {% endfor %}
                    </ul>
                    <div class="writeup-short-body">
                        {{summary.summary_content|truncatechars_html:100|safe}}
                    </div>
                </div>




    {% empty %}
            <h3>Ooops!</h3>
            <p>Looks like this character hasn't done enough adventuring yet!</p>

    {% endfor %}
    </div>

{% endblock %}

templates/writeups/index_writeups.html
{% extends 'opentable/base.html' %}

{% block content %}

    <ul class="pagination">
    {% if writeups.has_previous %}
    <li><a href="?page={{ writeups.previous_page_number }}">Back</a></li>
    {% else %}
        <li class="disabled"><a href="#">Back</a></li>
    {% endif %}



        {% for p in pages %}

        {% if p == writeups.number %}
            <li class="active"><a href="#">{{ writeups.number }}</a></li>
        {% else %}
            <li><a href="?page={{ p }}">{{ p }}</a></li>
        {% endif %}

        {% endfor %}


    {% if writeups.has_next %}
       <li><a href="?page={{ writeups.next_page_number }}">Next</a></li>
    {% else %}
        <li class="disabled"><a href="#">Next</a></li>
    {% endif %}
    </ul>

    <div class="writeups-list">
        {% for writeup, count in writeups_and_comment_counts %}
            <div class="writeup-short">
                <a href="{% url 'writeups:show_writeup' writeup.id %}"><h4>{{writeup.author_character}}</h4></a>
                <h6 class="writeup-meta">by {{writeup.author}} on {{writeup.date_added}}</h6>

                <div class="writeup-short-body">
                    {{writeup.post_content|truncatechars_html:200|safe}}
                    <span class="writeup-meta">Comments <span class="badge">{{count}}</span></span>
                </div>
            </div>

        {% empty %}



            <h3>Ooops!</h3>
            <p>No write ups here yet.</p>

    {% endfor %}
    </div>


{% endblock %}

templates/writeups/list_summaries.html
{% extends 'opentable/base.html' %}

{% block content %}

  <ul class="pagination">
    {% if summaries.has_previous %}
    <li><a href="?page={{ writeups.previous_page_number }}">Back</a></li>
    {% else %}
        <li class="disabled"><a href="#">Back</a></li>
    {% endif %}

        {% for p in pages %}

        {% if p == summaries.number %}
            <li class="active"><a href="#">{{ summaries.number }}</a></li>
        {% else %}
            <li><a href="?page={{ p }}">{{ p }}</a></li>
        {% endif %}

        {% endfor %}

    {% if summaries.has_next %}
       <li><a href="?page={{ writeups.next_page_number }}">Next</a></li>
    {% else %}
        <li class="disabled"><a href="#">Next</a></li>
    {% endif %}
    </ul>

    <div class="writeups-list">
        {% for summary in summaries %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="row">
                        <div class="col-sm-6">
                            <a href="{% url 'writeups:show_summary' summary.id %}"><h4>Session {{summary.number}}</h4></a>
                            <h6>{{summary.location}}</h6>
                            <h6 class="writeup-meta">by {{summary.gm}} on {{summary.date_added}}</h6>
                        </div>
                        <div class="col-sm-6">
                            <ul class="list-inline pull-right">
                            {% for char in summary.session_characters.all %}
                                <!-- TODO: make these links to character stats pages - with tool tips! -->
                                <li><img class="character-token-small" src="{{MEDIA_URL}}/{{char.character_token}}"></li>
                            {% endfor %}
                            </ul>
                        </div>
                        </div>
                    </div>
                    <div class="panel-body">
                        {{summary.summary_content|truncatechars_html:100|safe}}
                    </div>
                </div>




    {% empty %}
            <h3>Ooops!</h3>
            <p>Looks like this character hasn't done enough adventuring yet!</p>

    {% endfor %}
    </div>

{% endblock %}

templates/writeups/list_writeups.html
{% extends 'opentable/base.html' %}

{% block content %}

{% load crispy_forms_tags %}

{% load writeup_extras %}

<div class="col-xs-12">
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn" data-toggle="modal" data-target="#search-writeups-modal">
  <span class="glyphicon glyphicon-search"></span>
</button>

<!-- Modal -->
<div class="modal" id="search-writeups-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Search Write Ups</h4>
      </div>
      <div class="modal-body">
        {% crispy search_form search_form.helper %}
      </div>
    </div>
  </div>
</div>
</div>


<!--
<div class="row">
    <div class="col-sm-12 search-bar">

    </div>

</div>
-->
<!--
<div class="col-xs-12">
    <div class="btn-group" role="'group">
        <a href="#" type="button" id="sort-newest" class="btn btn-default btn-sm">Sort All Newest</a>
        <a href="#" type="button" id="sort-oldest" class="btn btn-default btn-sm">Sort All Oldest</a>
        <a href="#" id="reverse-page-order" type="button" class="btn btn-default btn-sm">Reverse Page Order</a>
    </div>
</div>
-->

<div class="col-xs-12">
    <ul class="pagination">
    {% if writeups.has_previous %}
    <li><a href="?{{ request.GET.urlencode }}&page={{ writeups.previous_page_number }}">Back</a></li>
    {% else %}
        <li class="disabled"><a href="#">Back</a></li>
    {% endif %}



        {% for p in pages %}

        {% if p == writeups.number %}
            <li class="active"><a href="#">{{ writeups.number }}</a></li>
        {% else %}
            <li><a href="?{{ request.GET.urlencode }}&page={{ p }}">{{ p }}</a></li>
        {% endif %}

        {% endfor %}


    {% if writeups.has_next %}
       <li><a href="?{{ request.GET.urlencode }}&page={{ writeups.next_page_number }}">Next</a></li>
    {% else %}
        <li class="disabled"><a href="#">Next</a></li>
    {% endif %}
    </ul>
</div>



    <div class="col-xs-11 col-xs-offset-1">

        <div id="to-be-sorted">
        {% for writeup in writeups %}
            <div class="panel panel-default">
                <div class="panel-heading"><a href="{% url 'writeups:show_writeup' writeup.id %}"><h5>{{writeup.author_character}}</h5></a>
                <span class="writeup-meta">by {{writeup.author}} on {{writeup.date_added}}</span>
                </div>

                <div class="panel-body">
                    <p>{{writeup.post_content|replace_linebr|truncatewords_html:80|safe}}</p>
                </div>
            </div>

        {% empty %}
            <h3>Ooops!</h3>
            <p>No write ups here yet.</p>

        {% endfor %}
        </div>
    </div>


{% endblock %}

templates/writeups/show_summary.html
{% extends 'opentable/base.html' %}


{% block content %}


    <div class="panel panel-default writeup-box">
<div class="gear-menu">
            {% if user.is_authenticated %}
                {% if user == this_summary.gm or user.is_superuser %}
                    <div class="btn-group" role="group">
                        <a href="{% url 'writeups:edit_summary' this_summary.id %}" type="button" class="btn btn-default btn-sm" aria-label="edit" data-toggle="tooltip" data-original-title="Edit">
                            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                        </a>

                        <a href="{% url 'writeups:delete_summary' this_summary.id  %}" type="button" class="btn btn-default btn-sm" aria-label="delete" data-toggle="tooltip" data-original-title="Delete">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </a>
                    </div>
                {% endif %}
            {% endif %}
        </div>
        <h3>Session {{this_summary.number}}</h3>
        <h6 class="writeup-meta">GMed by {{this_summary.gm}} on {{this_summary.date_added}}</h6>
        <h5>Location: {{this_summary.location}}</h5>

        <ul class="list-inline">
            <li><h5>PCs:</h5></li>
            {% for char in this_summary.session_characters.all %}
                <li><h6 class="character-token-label">{{char.name}}</h6><img class="character-token-small" src="{{MEDIA_URL}}/{{char.character_token}}"></li>
            {% endfor %}
        </ul>
        <div class="writeup-text">
            <h5>Summary:</h5>
            {{this_summary.summary_content|safe}}
        </div>
        <h6>XP Awarded: {{this_summary.xp_awarded}}</h6>
        <h6>Important NPCs: {{this_summary.important_npcs}}</h6>
    </div>


{% endblock %}

<!-- TODO: continue to refine look of summary index and summary single view-->
<!-- TODO: make images in show summary links to characters stats page -->

templates/writeups/show_writeup.html
{% extends 'opentable/base.html' %}


{% block content %}


    <div class="panel panel-default writeup-box">
        <!-- if user == this_writeup.author or user.is_superuser-->
        <div class="gear-menu">
            <div class="btn-group" role="group">
            {% if previous_writeup %}
            <a href="{% url 'writeups:show_writeup' previous_writeup.id %}" type="button" class="btn btn-default btn-sm" aria-label="previous-writeup">Prev</a>
            {% else %}
            <a href="#" type="button" class="btn btn-default btn-sm disabled" aria-label="previous-writeup">Prev</a>
            {% endif %}
            {% if next_writeup %}
            <a href="{% url 'writeups:show_writeup' next_writeup.id %}" type="button" class="btn btn-default btn-sm" aria-label="next-writeup">Next</a>
            {% else %}
            <a href="#" type="button" class="btn btn-default btn-sm disabled" aria-label="next-writeup">Next</a>
            {% endif %}
        </div>
            {% if user.is_authenticated %}
                {% if user == this_writeup.author or user.is_superuser %}
                    <div class="btn-group" role="group">
                        <a href="{% url 'writeups:edit_writeup' this_writeup.id %}" type="button" class="btn btn-default btn-sm" aria-label="edit" data-toggle="tooltip" data-original-title="Edit">
                            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                        </a>

                        <a href="{% url 'writeups:delete_writeup' this_writeup.id  %}" type="button" class="btn btn-default btn-sm" aria-label="delete" data-toggle="tooltip" data-original-title="Delete">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </a>
                    </div>
                {% endif %}
            {% endif %}

        </div>
        <h4>{{this_writeup.author_character}}</h4>
        <h6 class="writeup-meta">by {{this_writeup.author|capfirst}} on {{this_writeup.date_added}}</h6>
        <div class="writeup-text">
            {{this_writeup.post_content|safe}}
        </div>


    </div>
    {% if this_writeup_comments|length > 0 %}
    <h4>Comments:</h4>
    <div class="panel panel-default comments-section">

        {% for comment in this_writeup_comments %}
            <div class="comment-box">
                {% if user.is_authenticated %}
                    {% if user == comment.author or user.is_superuser %}
                        <div class="gear-menu">
                            <div class="btn-group" role="group">
                                <a href="{% url 'writeups:edit_comment' this_writeup.id comment.id %}"type="button" class="btn btn-default btn-sm" aria-label="edit" data-toggle="tooltip" data-original-title="Edit">
                                    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                                </a>
                                <a href="{% url 'writeups:delete_comment' this_writeup.id comment.id %}"type="button" class="btn btn-default btn-sm" aria-label="delete" data-toggle="tooltip" data-original-title="Delete">
                                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                </a>
                            </div>
                        </div>
                    {% endif %}
                {% endif %}
                <div class="comment-text">
                    {{comment.comment_content|safe}}
                </div>
                <div class="comment-meta">
                    by {{comment.author|capfirst}} on {{comment.date_added}}
                </div>
            </div>
        {% endfor %}
    </div>
    {% else %}
    <h4>No comments yet...</h4>
    {% endif %}

    {% if user.is_authenticated %}
    <div class="comment-form">
        {% load crispy_forms_tags %}
        <div class="row">
                {% crispy comment_form comment_form.helper %}
        </div>

    </div>
    {% endif %}


{% endblock %}