characters/urls.py
__author__ = 'davidkavanagh'

from django.conf.urls import patterns, url
from characters import views

urlpatterns = patterns('',
    # Examples:
    url(r'^listCharacters/$', views.list_characters, name='list_characters'),
    url(r'^showCharacter/(?P<character_id>\d+)/$', views.show_character, name='show_character'),
    url(r'^addCharacter/$', views.add_character, name='add_character'),
    url(r'^editCharacter/(?P<character_id>\d+)/$', views.add_character, name='edit_character'),
    url(r'^deleteCharacter/(?P<character_id>\d+)/$', views.delete_character, name='delete_character'),
    url(r'^addXP/(?P<character_id>\d+)/$', views.add_xp, name='add_xp'),
)

opentable/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from opentable import views

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'opentable.views.home', name='home'),
    url(r'^', include('characters.urls', namespace='characters')),
    url(r'^writeups/', include('writeups.urls', namespace='writeups')),
    url(r'^campaigns/', include('campaigns.urls', namespace='campaigns')),
    url(r'^players/', include('players.urls', namespace='players')),
    url(r'^numbers/', 'opentable.views.numbers', name='numbers'),
    url(r'^about/', 'opentable.views.about', name='about'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', 'opentable.views.user_login', name='login'),
    url(r'^logout/', 'opentable.views.user_logout', name='logout'),
    url(r'^register/', 'opentable.views.register_new_user', name='register_new_user'),
    url(r'^changePassword/(?P<user_id>\d+)/$', 'opentable.views.change_password', name='change_password'),
    url(r'^tinymce/', include('tinymce.urls')),

)


if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
    )

players/urls.py
__author__ = 'davidkavanagh'

from django.conf.urls import patterns, url
from players import views

urlpatterns = patterns('',
                       # Examples:
                       url(r'^listPlayers/$', views.list_players, name='list_players'),
                       url(r'^showPlayer/(?P<user_id>\d+)/$', views.show_player, name='show_player'),
                       # url(r'^addplayer/$', views.add_player, name='add_player'),
                       # url(r'^editplayer/(?P<player_id>\d+)/$', views.edit_player, name='edit_player'),
                       # url(r'^deleteplayer/(?P<player_id>\d+)/$', views.delete_player, name='delete_player'),
                       )

characters/models.py
from django.db import models
from django.contrib.auth.models import User

from campaigns.models import Campaign

# Create your models here.


class Character(models.Model):

    PC = ('PC', 'PC')
    NPC = ('NP', 'NPC')
    ORG = ('OR', 'Organisation')

    type_choices = [
        PC,
        NPC,
        ORG
    ]

    character_type = models.CharField(max_length=2, choices=type_choices, default=PC[0])

    campaign = models.ForeignKey(Campaign)

    player = models.ForeignKey(User)

    name = models.CharField(max_length=100)

    race = models.CharField(max_length=100)

    character_class = models.CharField(max_length=100)

    level = models.IntegerField(default=1)

    biography = models.TextField()

    current_xp = models.BigIntegerField()

    deceased = models.BooleanField(default=False)

    num_deaths = models.IntegerField(default=0)

    character_token = models.ImageField(upload_to='tokens')

    date_added = models.DateTimeField(auto_now_add=True, auto_now=False)

    last_edited = models.DateTimeField(auto_now_add=False, auto_now=True)

    hidden = models.BooleanField(default=False)

    def __unicode__(self):

        return self.name

    class Meta:
        ordering = ('name',)

characters/forms.py
__author__ = 'David Kavanagh'

from .models import Character
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Div, Field
from crispy_forms.bootstrap import InlineField
from django import forms
from django.contrib.auth.models import User

from campaigns.models import Campaign


class CharacterForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):

        super(CharacterForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_class = 'bootstrap3'
        self.helper.form_method = 'POST'
        self.helper.form_action = "/addCharacter/"
        self.helper.form_enctype = "multipart/form-data"

        row1 = Div(
            Div('player', css_class='col-md-3',),
            Div('campaign', css_class='col-md-3'),
            Div('character_type', css_class='col-md-3',),
            Div('name', css_class='col-md-3',),
            css_class='row',
        )

        row2 = Div(
            Div('race', css_class='col-md-3',),
            Div('character_class', css_class='col-md-3',),
            Div('level', css_class='col-md-3',),
            Div('current_xp', css_class='col-md-3'),
            css_class='row',
        )

        row3 = Div(Div('biography', css_class='col-md-12'),css_class='row')

        row4 = Div(
            Div('character_token', css_class='col-md-4'),
            Div('num_deaths', css_class='col-md-4',),
            Div('deceased', css_class='col-md-2',),
            Div('hidden', css_class='col-md-2'),
            css_class='row',
        )

        self.helper.layout = Layout(
            row1,
            row2,
            row3,
            row4
        )

        self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = Character
        fields = [
            'player', 'campaign', 'character_type', 'name', 'race', 'character_class',
            'level', 'biography', 'current_xp', 'deceased',
            'num_deaths', 'character_token', 'hidden'
        ]


class CharacterSearchForm(forms.Form):

    player = forms.ModelChoiceField(required=False, queryset=User.objects.all())

    campaigns = Campaign.objects.all()
    campaign = forms.ModelChoiceField(required=False, queryset=campaigns, initial=campaigns[0])

    PC = ('PC', 'PC')
    NPC = ('NP', 'NPC')
    ORG = ('OR', 'Organisation')
    ALL = ('AL', 'All')

    type_choices = [
        PC,
        NPC,
        ORG,
        ALL
    ]

    type_choices = type_choices

    type = forms.ChoiceField(required=False,
                             choices=type_choices)

    search = forms.CharField(required=False)
    deceased_choices = [
        ('a', 'All'),
        ('d', 'Dead'),
        ('n', 'Not Dead')
    ]

    deceased = forms.ChoiceField(required=False,
                                 choices=deceased_choices)

    def __init__(self, *args, **kwargs):
        super(CharacterSearchForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form'
        self.helper.field_template = 'bootstrap3/layout/inline_field.html'
        self.helper.form_method = 'Get'
        self.helper.form_action = "/listCharacters/"
        self.helper.layout = Layout(
            Div(
                Div('campaign', css_class="col-md-6",),
                Div('player', css_class="col-md-6",)
            ),
            Div(
                Div('type', css_class="col-md-6",),
                Div('deceased', css_class="col-md-6",),
            ),
            Div('search', css_class="col-md-12",),
            Submit('Submit', 'Search'),
        )

    class Meta:
        fields = ['campaign', 'player', 'type', 'deceased', 'search']

characters/views.py
from django.shortcuts import render_to_response, RequestContext
from django.http import HttpResponseRedirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required


from opentable.views import is_gm
from characters.models import Character
from characters.forms import CharacterForm, CharacterSearchForm
from writeups.models import Writeup, SessionSummary

# Create your views here.


#dictionary to hold leveling up XP costs
levels = {
         '1': 0,        '2': 2000,     '3': 5000,     '4': 9000,
         '5': 15000,    '6': 23000,    '7': 35000,    '8': 51000,
         '9': 75000,    '10': 105000,  '11': 155000,  '12': 220000,
         '13': 315000,  '14': 445000,  '15': 635000,  '16': 890000,
         '17': 1300000, '18': 1800000, '19': 2550000, '20': 3600000
}


def list_characters(request):

    characters = Character.objects.all()

    if request.method == 'GET':

        search_player = request.GET.get('player', None)

        search_campaign = request.GET.get('campaign', None)
        search_text = request.GET.get('search', None)
        search_deceased = request.GET.get('deceased', None)
        search_type = request.GET.get('type', None)

        if search_player:
            characters = characters.filter(player__pk=search_player)

        if search_campaign:
            characters = characters.filter(campaign__pk=search_campaign)

        if search_type:
            if search_type !='AL':
                characters = characters.filter(character_type=search_type)

        if search_deceased:
            if search_deceased == 'a':
                pass
            elif search_deceased == 'd':
                characters = characters.filter(deceased=True)
            else:
                characters = characters.filter(deceased=False)

        if search_text:
            characters = characters.filter(Q(name__icontains=search_text) |
                                           Q(character_class__icontains=search_text) |
                                           Q(race__icontains=search_text))

        search_form = CharacterSearchForm(request.GET)

    else:

        characters = characters.filter(character_type='PC')

        search_form = CharacterSearchForm(None)

    if not is_gm(request.user):
        characters = characters.filter(hidden=False)

    data = {'characters': characters, 'search_form': search_form}

    return render_to_response('characters/list_character.html', data, context_instance=RequestContext(request))


def show_character(request, character_id):

    this_character = Character.objects.get(pk=character_id)

    sessions_in = SessionSummary.objects.filter(session_characters__pk=character_id).count()
    sessions_all = SessionSummary.objects.all().count()

    character_writeups = Writeup.objects.filter(author_character__pk=character_id).count()

    if this_character.level < 20:
        xp_to_next_level = levels[str(this_character.level+1)] - this_character.current_xp
    else:
        xp_to_next_level = '+++'

    characters = Character.objects.all()
    data = {'this_character': this_character, 'characters': characters,
            'sessions_in': sessions_in, 'sessions_all': sessions_all,
            'xp_to_next_level': xp_to_next_level,
            'character_writeups': character_writeups}

    return render_to_response('characters/show_character.html', data, context_instance=RequestContext(request))


@login_required
def add_character(request, character_id=None):

    if character_id is not None:
        this_character = Character.objects.get(pk=character_id)

    if request.method == "POST":
        if character_id is not None:
            character_form = CharacterForm(request.POST, request.FILES, instance=this_character)
            character_form.initial['player'] = this_character.player
        else:
            character_form = CharacterForm(request.POST, request.FILES)

        if character_form.is_valid():
            save_it = character_form.save(commit=False)
            if not request.user.is_superuser:
                save_it.player = request.user
            save_it.save()

            this_character = save_it
            redirect_to_url = '/showCharacter/{0}/'.format(this_character.id)

            return HttpResponseRedirect(redirect_to_url)

    else:
        if character_id is not None:
            character_form = CharacterForm(instance=this_character)
            character_form.initial['player'] = this_character.player
        else:
            character_form = CharacterForm()

    if character_id is not None:
        character_form.helper.form_action = '/editCharacter/' + character_id + '/'

    if not is_gm(request.user):
        """
        Note that non-GMs shouldn't be able to make hidden characters or edit the player choice
        """
        character_form.helper.layout[3].pop(3)
        character_form.fields.pop('hidden')
        character_form.fields['player'].choices = [(request.user.id, request.user.username)]


    data = {'character_form': character_form}

    return render_to_response('characters/add_character.html', data, context_instance=RequestContext(request))


def delete_character(request, character_id):

    this_character = Character.objects.get(pk=character_id)
    this_character.delete()

    return HttpResponseRedirect('/')


@login_required
def add_xp(request, character_id):

    # update model with new XP value
    this_character = Character.objects.get(pk=character_id)

    this_character.current_xp += int(request.POST['xp_to_add'])

    # level up
    if this_character.current_xp >= levels[str(int(this_character.level)+1)]:
        this_character.level += 1
        # if got enough XP to level up more than once, reset to XP to XP for next level - 1
        if this_character.current_xp >= levels[str(int(this_character.level)+1)]:
            this_character.current_xp = levels[str(int(this_character.level)+1)] - 1

    this_character.save()

    redirect_url = '/showCharacter/'+character_id+'/'
    return HttpResponseRedirect(redirect_url)

templates/characters/characterIndex.html
{% extends 'opentable/base.html' %}

{% block custom_header_scripts %}

<script type="text/javascript">
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip({
        placement : 'top'
    });
});
</script>

{% endblock %}


{% block content %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-sm-6 col-sm-offset-3 search-bar">
            {% crispy search_form search_form.helper %}
    </div>
</div>

    {% for character in characters %}
    {% if forloop.first %}
        <div class="row">
    {% endif %}


    <div class="col-sm-4">

        <div class="character-index-box panel panel-default">

            <div class="row">
                <div class="col-md-12">
                    <h4 class="character-token-label">{{character.name}}</h4>
                    <h6>{{character.character_class}} - Level {{character.level}}</h6>
                </div>
            </div>


            <div class="row">
                <div class="col-md-12">
                    <a href="{% url 'characters:show_character' character.id %}"><img class="character-token-big" src="{{MEDIA_URL}}/{{character.character_token}}"></a>
                </div>
            </div>

            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="btn-toolbar character-buttons" role="toolbar">
                        <div class="btn-group" role="group">
                            <a href="{% url 'characters:show_character' character.id %}" type="button" class="btn btn-default btn-xs" aria-label="stats" data-toggle="tooltip" data-original-title="Stats">
                                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                            </a>

                            <a href="{% url 'writeups:character_list_writeups' character.id  %}" type="button" class="btn btn-default btn-xs" aria-label="writeups" data-toggle="tooltip" data-original-title="Write ups">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            </a>

                            <a href="{% url 'writeups:character_list_summaries' character.id  %}" type="button" class="btn btn-default btn-xs" aria-label="sessions" data-toggle="tooltip" data-original-title="Session Summaries">
                                <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
                            </a>
                        </div>
                        {% if user.is_authenticated %}
                            {% if user == character.player or user.is_superuser %}
                                <div class="btn-group" role="group">
                                    <a href="{% url 'characters:edit_character' character.id %}" type="button" class="btn btn-default btn-xs" aria-label="edit" data-toggle="tooltip" data-original-title="Edit">
                                        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                                    </a>

                                    <a href="{% url 'characters:delete_character' character.id  %}" type="button" class="btn btn-default btn-xs" aria-label="delete" data-toggle="tooltip" data-original-title="Delete">
                                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                    </a>
                                </div>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>









            <!--
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{% url 'characters:show_character' character.id %}">Stats</a></li>
                                <li><a href="{% url 'writeups:character_list_writeups' character.id %}">Write Ups</a></li>
                                <li><a href="{% url 'writeups:character_list_summaries' character.id %}">Sessions</a></li>

                                        <li class="divider"></li>
                                        <li><a href="{% url 'characters:edit_character' character.id %}">Edit</a></li>
                                        <li><a href="{% url 'characters:delete_character' character.id %}">Delete</a></li>

                            </ul>
            -->


            </div>
    </div>


    {% if forloop.counter|divisibleby:"3" and not forloop.last%}
    </div>
    <div class="row">
    {% endif %}

    {% if forloop.last %}
        </div>
    {% endif %}


    {% endfor %}





{% endblock %}

templates/characters/characterStats.html
{% extends 'opentable/base.html' %}

{% block content %}


<div class="panel panel-default writeup-box">
    {% if user.is_authenticated %}
        {% if user.is_superuser %}
            <div class="dropdown gear-menu">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                    <img class="icon" src="{{MEDIA_URL}}/images/gear.png">
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'characters:edit_character' this_character.id %}">Edit</a></li>
                    <li><a href="{% url 'characters:delete_character' this_character.id %}">Delete</a></li>
                </ul>
            </div>
        {% endif %}
    {% endif %}
    <h4>{{this_character.name}}</h4>
    <a class="btn btn-primary" href="{% url 'writeups:character_list_writeups' this_character.id %}">Write Ups</a>
    <a class="btn btn-primary" href="{% url 'writeups:character_list_summaries' this_character.id %}">Sessions</a>
    <div class="row writeup-box">
        <div class="col-md-4 writeup-box-column">
            <img class="character-token-big" src="{{MEDIA_URL}}/{{this_character.character_token}}">
        </div>
        <div class="col-md-4 writeup-box-column">
            <h5>Played by {{this_character.player|capfirst}}</h5>
            <h5>Race: {{this_character.race}}</h5>
            <h5>Class: {{this_character.character_class}}</h5>
            <h5>Level {{this_character.level}}</h5>


        </div>
        <div class="col-md-4 writeup-box-column">
            <h5>Games Played: {{sessions_in}}/{{sessions_all}}</h5>
            <h5>Write Ups: {{character_writeups}}</h5>
            <h5>Current XP: {{this_character.current_xp}}</h5>
            <h5>XP to Next level: {{xp_to_next_level}} </h5><!-- TODO: javascript to work this out I think -->
            <div class="row">
            <form class="form-inline" method="POST" action="{% url 'characters:add_xp' this_character.id%}">
                {% csrf_token %}
                    <input type="number" class="form-control col-sm-6" name="xp_to_add" placeholder="XP Gained">
                    <button type="submit" class="btn btn-primary">Add XP</button>
            </form>

            </div>
        </div>
    </div>

    <div class="character-bio writeup-box">
        <h5>Character Summary:</h5>
        {{this_character.biography|safe}}

    </div>
</div>

</script>

{% endblock %}

templates/characters/index_character.html
{% extends 'opentable/base.html' %}

{% block custom_header_scripts %}



{% endblock %}


{% block content %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-sm-9 search-bar">
            {% crispy search_form search_form.helper %}
    </div>

</div>
<div class="container-fluid">
    {% for character in characters %}
        <div class="col-xs-12 col-sm-6 col-md-4">
            <div class="character-index-box panel panel-default">

                <h5 class="character-token-label">{{character.name}}</h5>
                <h6>{{character.character_class}} - Level {{character.level}}</h6>

                <a href="{% url 'characters:show_character' character.id %}"><img class="character-token-big" src="{{MEDIA_URL}}/{{character.character_token}}"></a>

                <div class="row">
                    <div class="col-sm-8 col-sm-offset-2">
                        <div class="btn-toolbar character-buttons" role="toolbar">
                            <div class="btn-group" role="group">
                                <a href="{% url 'characters:show_character' character.id %}" type="button" class="btn btn-default btn-xs" aria-label="stats" data-toggle="tooltip" data-original-title="Stats">
                                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                                </a>

                                <a href="{% url 'writeups:character_list_writeups' character.id  %}" type="button" class="btn btn-default btn-xs" aria-label="writeups" data-toggle="tooltip" data-original-title="Write ups">
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                </a>

                                <a href="{% url 'writeups:character_list_summaries' character.id  %}" type="button" class="btn btn-default btn-xs" aria-label="sessions" data-toggle="tooltip" data-original-title="Session Summaries">
                                    <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
                                </a>
                            </div>
                            {% if user.is_authenticated %}
                                {% if user == character.player or user.is_superuser %}
                                    <div class="btn-group" role="group">
                                        <a href="{% url 'characters:edit_character' character.id %}" type="button" class="btn btn-default btn-xs" aria-label="edit" data-toggle="tooltip" data-original-title="Edit">
                                            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                                        </a>

                                        <a href="{% url 'characters:delete_character' character.id  %}" type="button" class="btn btn-default btn-xs" aria-label="delete" data-toggle="tooltip" data-original-title="Delete">
                                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                        </a>
                                    </div>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

templates/characters/list_character.html
{% extends 'opentable/base.html' %}

{% block custom_header_scripts %}

{% endblock %}


{% block content %}

{% load crispy_forms_tags %}
<div class="search-bar">
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn" data-toggle="modal" data-target="#character-search-modal">
  <span class="glyphicon glyphicon-search"></span>
</button>
</div>

<!-- Modal -->
<div class="modal" id="character-search-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Search Characters</h4>
      </div>
      <div class="modal-body">
        {% crispy search_form search_form.helper %}
      </div>
    </div>
  </div>
</div>

<div class="container-fluid">
    {% for character in characters %}
        <div class="col-xs-12 col-sm-6 col-md-4">
            <div class="character-index-box panel panel-default">

                <h5 class="character-token-label">{{character.name}}</h5>
                <h6>{{character.character_class}} - Level {{character.level}}</h6>

                <a href="{% url 'characters:show_character' character.id %}"><img class="character-token-big" src="{{MEDIA_URL}}/{{character.character_token}}"></a>

                <div class="row">
                    <div class="col-sm-8 col-sm-offset-2">
                        <div class="btn-toolbar character-buttons" role="toolbar">
                            <div class="btn-group" role="group">
                                <a href="{% url 'characters:show_character' character.id %}" type="button" class="btn btn-default btn-xs" aria-label="stats" data-toggle="tooltip" data-original-title="Stats">
                                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                                </a>

                                <a href="{% url 'writeups:list_writeups' %}?character={{character.id}}" type="button" class="btn btn-default btn-xs" aria-label="writeups" data-toggle="tooltip" data-original-title="Write ups">
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                </a>

                                <a href="{% url 'writeups:character_list_summaries' character.id  %}" type="button" class="btn btn-default btn-xs" aria-label="sessions" data-toggle="tooltip" data-original-title="Session Summaries">
                                    <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
                                </a>
                            </div>
                            {% if user.is_authenticated %}
                                {% if user == character.player or user.is_superuser %}
                                    <div class="btn-group" role="group">
                                        <a href="{% url 'characters:edit_character' character.id %}" type="button" class="btn btn-default btn-xs" aria-label="edit" data-toggle="tooltip" data-original-title="Edit">
                                            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                                        </a>

                                        <a href="{% url 'characters:delete_character' character.id  %}" type="button" class="btn btn-default btn-xs" aria-label="delete" data-toggle="tooltip" data-original-title="Delete">
                                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                        </a>
                                    </div>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

templates/characters/show_character.html
{% extends 'opentable/base.html' %}

{% block content %}


<div class="panel panel-default writeup-box">

    <div class="gear-menu">
        <div class="btn-group">
            <a href="{% url 'writeups:list_writeups' %}?character={{this_character.id}}"type="button" class="btn btn-default btn-sm" aria-label="edit" data-toggle="tooltip" data-original-title="Write Ups">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </a>
            <a href="{% url 'writeups:character_list_summaries' this_character.id %}"type="button" class="btn btn-default btn-sm" aria-label="edit" data-toggle="tooltip" data-original-title="Sessions">
                <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
            </a>
        </div>

    
            {% if user.is_authenticated %}
                {% if user == this_character.player or user.is_superuser %}
                    <div class="btn-group" role="group">
                        <a href="{% url 'characters:edit_character' this_character.id %}" type="button" class="btn btn-default btn-sm" aria-label="edit" data-toggle="tooltip" data-original-title="Edit">
                            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                        </a>

                        <a href="{% url 'characters:delete_character' this_character.id  %}" type="button" class="btn btn-default btn-sm" aria-label="delete" data-toggle="tooltip" data-original-title="Delete">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </a>
                    </div>
                {% endif %}
            {% endif %}
        </div>

    <h4>{{this_character.name}}</h4>
    <!-- TODO: change these buttons to glyph buttons -->

    <div class="row writeup-box">
        <div class="col-md-4 writeup-box-column">
            <img class="character-token-big" src="{{MEDIA_URL}}/{{this_character.character_token}}">
        </div>
        <div class="col-md-4 writeup-box-column">
            <h6>Played by {{this_character.player|capfirst}}</h6>
            <h6>Race: {{this_character.race}}</h6>
            <h6>Class: {{this_character.character_class}}</h6>
            <h6>Level {{this_character.level}}</h6>
            {% if this_character.deceased %}
                <h6>Currently Dead</h6>
            {% endif %}
            <h6>Number of Deaths: {{this_character.num_deaths}}</h6>


        </div>
        <div class="col-md-4 writeup-box-column">
            <h6>Games Played: {{sessions_in}}/{{sessions_all}}</h6>
            <h6>Write Ups: {{character_writeups}}</h6>
            <h6>Current XP: {{this_character.current_xp}}</h6>
            <h6>XP to Next level: {{xp_to_next_level}} </h6>
            <div class="row">
            <form class="form-inline" method="POST" action="{% url 'characters:add_xp' this_character.id%}">
                {% csrf_token %}
                    <input type="number" class="form-control col-sm-6" name="xp_to_add" placeholder="XP Gained">
                    <button type="submit" class="btn btn-primary">Add XP</button>
            </form>

            </div>
        </div>
    </div>

    <div class="character-bio writeup-box">
        <h5>Character Summary:</h5>
        {{this_character.biography|safe}}

    </div>
</div>

</script>

{% endblock %}